class UsersConstants:
    __slots__ = ()
    CUSTOMUSER_EMAIL_LENGTH = 254
    CUSTOMUSER_USERNAME_LENGTH = 150
    CUSTOMUSER_FIRST_NAME_LENGTH = 150
    CUSTOMUSER_LAST_NAME_LENGTH = 150
    CUSTOMUSER_PASSWORD_LENGTH = 150


class RecipesConstants:
    __slots__ = ()
    TAG_NAME_LENGTH = 32
    TAG_SLUG_LENGTH = 32
    INGREDIENT_NAME_LENGTH = 128
    INGREDIENT_MEASUREMENT_UNIT_LENGTH = 64
    RECIPE_NAME_LENGTH = 256
