version: '3.3'

volumes:
  pg_data:
  static:
  media:
  docs:
  frontend:

services:

  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    image: olgalevadnaya/foodgram_back
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    container_name: foodgram-front
    image: olgalevadnaya/foodgram_front
    env_file: .env
    volumes:
      - frontend:/app/result_build/

  gateway:
    container_name: foodgram-proxy
    image: olgalevadnaya/foodgram_proxy
    ports:
      - "8080:80"
    volumes:
      - frontend/build:/usr/share/nginx/html/
      - docs:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
      - frontend
    restart: always
